## Escape special characters

YAML is very picky about how it takes a valid string, so we are replacing single and double quotes (and ampersands) with their HTML encoded equivilents. This makes them look not so readable in raw format, but they are parsed and rendered nicely.

In [35]:
html_escape_table = {
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;"
    }

def html_escape(text):
    """Produce entities within text."""
    return "".join(html_escape_table.get(c,c) for c in text)

# Publications markdown generator

Takes a .bib of publications with metadata and converts them for use with [academicpages.github.io](academicpages.github.io). This is an interactive Jupyter notebook ([see more info here](http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/what_is_jupyter.html)). The core python code is also in `publications.py`. Run either from the `markdown_generator` folder after replacing `publications.tsv` with one containing your data.

In [ ]:
import os
import calendar
from pybtex.database import parse_file

bib_data = parse_file('publications.bib')
#print(bib_data)

for entry in bib_data.entries:
# create the name of each md file
    year  = bib_data.entries[entry].fields['year']
    if 'month' in bib_data.entries[entry].fields:
        month = list(calendar.month_abbr).index(bib_data.entries[entry].fields['month'].capitalize())
    else:
        month = 1
    pub_date = str(year) + "-" + str(month) + "-" + "1"
    
    md_filename   = pub_date + "-" + entry + ".md"
    #print(md_filename)

# cp pdf files to ../files and set up the link
    if 'file' in bib_data.entries[entry].fields:
        path = '/mnt/c' + bib_data.entries[entry].fields['file'][15:-4]
        path = path.replace(" ",    "\ ")
        path = path.replace("{\_}", "\_")
        os.system('cp ' + path + ' ../files')
        html_filename = '/files/' + os.path.basename(path).replace("\\", "")
    else:
        html_filename = ''
    #print(html_filename)

# set up author names
    num_author=len(bib_data.entries[entry].persons['author'])
    for count, author in enumerate(bib_data.entries[entry].persons['author']):
        if count == 0:
            author_list = author.last_names[0] + ", "
            for cc, first in enumerate(author.bibtex_first_names):
                if cc <len(author.bibtex_first_names)-1:
                    author_list += first + " "
                else:
                    author_list += first
        elif count < num_author-1:
            author_list += ", " 
            for cc, first in enumerate(author.bibtex_first_names):
                if cc <len(author.bibtex_first_names)-1:
                    author_list += first + " "
                else:
                    author_list += first
            author_list += " " + author.last_names[0]
        else:
            author_list += " and " 
            for cc, first in enumerate(author.bibtex_first_names):
                if cc <len(author.bibtex_first_names)-1:
                    author_list += first + " "
                else:
                    author_list += first
            author_list += " " + author.last_names[0]
        author_list = author_list.replace("{","")
        author_list = author_list.replace("}","")
    #print(author_list)

# set up the citation after the journal names
    citation = "<i>" + bib_data.entries[entry].fields['journal'] + "</i>"
    if 'volume' in bib_data.entries[entry].fields:
        citation += ", " + bib_data.entries[entry].fields['volume']
    if 'pages' in bib_data.entries[entry].fields:
        citation += ", " + bib_data.entries[entry].fields['pages']
    citation +=  ", doi:" + bib_data.entries[entry].fields['doi']
    citation += "." 
#    print(citation)
    
    ## YAML variables
    
    md = "---\ntitle: \"" + html_escape(bib_data.entries[entry].fields['title'][1:-1]) + '"\n'
    
    md += """collection: publications"""
    
    md += """\npermalink: """ + html_filename

    md += "\nyear: " + str(year) 

    md += "\nauthor: " + str(author_list) 

    md += "\nvenue: '" + html_escape(bib_data.entries[entry].fields['journal']) + "'"
    
    md += "\npaperurl: '" + bib_data.entries[entry].fields['url'] + "'"
    
    md += "\ncitation: '" + html_escape(citation) + "'"
    
    md += "\n---"
    
    ## Markdown description for individual page
    
    md_filename = os.path.basename(md_filename)
       
    with open("../_publications/" + md_filename, 'w') as f:
        f.write(md)
#    print(md)

# Publications markdown generator

Takes a CSV of publications with metadata and converts them for use with [academicpages.github.io](academicpages.github.io). This is an interactive Jupyter notebook ([see more info here](http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/what_is_jupyter.html)). The core python code is also in `publications.py`. Run either from the `markdown_generator` folder after replacing `publications.tsv` with one containing your data.

Output the Mendeley in .bib format first, and convert it to .csv using JabRef

In [43]:
!cat publications.csv

BibliographyType,ISBN,Identifier,Author,Title,Journal,Volume,Number,Month,Pages,Year,Address,Note,URL,Booktitle,Chapter,Edition,Series,Editor,Publisher,ReportType,Howpublished,Institution,Organizations,School,Annote,Custom1,Custom2,Custom3,Custom4,Custom5
7,"","Burrows2015","Burrows, D.  Alex; Chen, Gang; Sun, Lantao","Barotropic and Baroclinic Eddy Feedbacks in the Midlatitude Jet Variability and Responses to Climate Change–Like Thermal Forcings","Journal of the Atmospheric Sciences",74,1,"jan","111--132",2017,"","","http://journals.ametsoc.org/doi/10.1175/JAS-D-16-0047.1","","","","","","","","","","","","","","","","",""
7,"","Chen2007a","Chen, Gang; Held, Isaac M.; Robinson, Walter A.","Sensitivity of the Latitude of the Surface Westerlies to Surface Friction","Journal of the Atmospheric Sciences",64,8,"aug","2899--2915",2007,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS3995.1","","","","","","","","","","","","From Duplicate 2 (Sensitivity of the Latitude of the Surface Westerlies to Surface Friction - Chen, Gang; Held, Isaac M.; Robinson, Walter A.) From Duplicate 2 ( Sensitivity of the Latitude of the Surface Westerlies to Surface Friction - Chen, Gang; Held, Isaac M.; Robinson, Walter A ) ","","","","",""
7,"","Chen2007b","Chen, Gang; Held, Isaac M.","Phase speed spectra and the recent poleward shift of Southern Hemisphere surface westerlies","Geophysical Research Letters",34,21,"nov","L21805",2007,"","","http://doi.wiley.com/10.1029/2007GL031200","","","","","","","","","","","","From Duplicate 2 ( Phase speed spectra and the recent poleward shift of Southern Hemisphere surface westerlies - Chen, Gang; Held, Isaac M. ) ","","","","",""
7,"","Chen2008","Chen, Gang; Lu, Jian; Frierson, Dargan M. W.","Phase Speed Spectra and the Latitude of Surface Westerlies: Interannual Variability and Global Warming Trend","Journal of Climate",21,22,"nov","5942--5959",2008,"","","http://journals.ametsoc.org/doi/abs/10.1175/2008JCLI2306.1","","","","","","","","","","","","From Duplicate 2 (Phase Speed Spectra and the Latitude of Surface Westerlies: Interannual Variability and Global Warming Trend - Chen, Gang; Lu, Jian; Frierson, Dargan M. W.) From Duplicate 1 ( Phase Speed Spectra and the Latitude of Surface Westerlies: Interannual Variability and Global Warming Trend - Chen, Gang; Lu, Jian; Frierson, Dargan M. W. ) And Duplicate 4 ( Response of the Zonal Mean Atmospheric Circulation to El Ni{\~{n}}o versus Global Warming - Lu, Jian; Chen, Gang; Frierson, Dargan M. W. ) ","","","","",""
7,"","Chen2008b","Chen, Gang; Zurita-Gotor, Pablo","The Tropospheric Jet Response to Prescribed Zonal Forcing in an Idealized Atmospheric Model","Journal of the Atmospheric Sciences",65,7,"jul","2254--2271",2008,"","","http://journals.ametsoc.org/doi/abs/10.1175/2007JAS2589.1","","","","","","","","","","","","From Duplicate 1 (The tropospheric jet response to prescribed zonal forcing in an idealized atmospheric model - Chen, Gang; Zurita-Gotor, Pablo) From Duplicate 2 ( The tropospheric jet response to prescribed zonal forcing in an idealized atmospheric model - Chen, Gang; Zurita-Gotor, Pablo ) ","","","","",""
7,"","Chen2009","Chen, Gang; Plumb, R. Alan","Quantifying the Eddy Feedback and the Persistence of the Zonal Index in an Idealized Atmospheric Model","Journal of the Atmospheric Sciences",66,12,"dec","3707--3720",2009,"","","http://journals.ametsoc.org/doi/abs/10.1175/2009JAS3165.1","","","","","","","","","","","","","","","","",""
7,"","Chen2010","Chen, Gang; Plumb, R. Alan; Lu, Jian","Sensitivities of zonal mean atmospheric circulation to SST warming in an aqua-planet model","Geophysical Research Letters",37,12,"jun","",2010,"","","http://www.agu.org/pubs/crossref/2010/2010GL043473.shtml","","","","","","","","","","","","in press","","","","",""
7,"","Chen2011","Chen, Gang; Ming, Yi; Singer, Noah D.; Lu, Jian","Testing the Clausius-Clapeyron constraint on the aerosol-induced changes in mean and extreme precipitation","Geophysical Research Letters",38,,"feb","L04807",2011,"","","http://www.agu.org/pubs/crossref/2011/2010GL046435.shtml","","","","","","","","","","","","","","","","",""
7,"","Chen2011c","Chen, Gang; Sun, Lantao","Mechanisms of the Tropical Upwelling Branch of the Brewer–Dobson Circulation: The Role of Extratropical Waves","Journal of the Atmospheric Sciences",68,12,"dec","2878--2892",2011,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-11-044.1","","","","","","","","","","","","","","","","",""
7,"","Chen2013c","Chen, Gang; Lu, Jian; Sun, Lantao","Delineating the Eddy–Zonal Flow Interaction in the Atmospheric Circulation Response to Climate Forcing: Uniform SST Warming in an Idealized Aquaplanet Model","Journal of the Atmospheric Sciences",70,7,"jul","2214--2233",2013,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-12-0248.1","","","","","","","","","","","","","","","","",""
7,"","Chen2013d","Chen, Gang","The Mean Meridional Circulation of the Atmosphere Using the Mass above Isentropes as the Vertical Coordinate","Journal of the Atmospheric Sciences",70,7,"jul","2197--2213",2013,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-12-0239.1","","","","","","","","","","","","","","","","",""
7,"","Chen2014","Chen, Gang; Plumb, R. Alan","Effective Isentropic Diffusivity of Tropospheric Transport","Journal of the Atmospheric Sciences",71,9,"sep","3499--3520",2014,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-13-0333.1","","","","","","","","","","","","","","","","",""
7,"0094-8276","Chen2015","Chen, Gang; Lu, Jian; Burrows, D. Alex; Leung, L. Ruby","Local finite-amplitude wave activity as an objective diagnostic of midlatitude extreme weather","Geophysical Research Letters",42,24,"dec","10,952--10,960",2015,"","","http://doi.wiley.com/10.1002/2015GL066959","","","","","","","","","","","","","","","Blocking,Extreme weather,Local wave activity,Wave breaking","",""
7,"","Chen2017","Chen, Gang; Orbe, Clara; Waugh, Darryn W.","The role of monsoon-like zonally asymmetric heating in interhemispheric transport","Journal of Geophysical Research: Atmospheres",,,"","",2017,"","","http://doi.wiley.com/10.1002/2016JD026427","","","","","","","","","","","","","","","","",""
7,"","Domeisen2013","Domeisen, Daniela I. V.; Sun, Lantao; Chen, Gang","The role of synoptic eddies in the tropospheric response to stratospheric variability","Geophysical Research Letters",,,"sep","4933--4937",2013,"","","http://doi.wiley.com/10.1002/grl.50943","","","","","","","","","","","","","","","","",""
7,"","Fang2011a","Fang, Yuanyuan; Fiore, Arlene M.; Horowitz, Larry W.; Gnanadesikan, Anand; Held, Isaac; Chen, Gang; Vecchi, Gabriel; Levy, Hiram","The impacts of changing transport and precipitation on pollutant distributions in a future climate","Journal of Geophysical Research",116,D18,"sep","D18303",2011,"","","http://doi.wiley.com/10.1029/2011JD015642","","","","","","","","","","","","","","","","",""
7,"","Frierson2007b","Frierson, Dargan M. W.; Lu, Jian; Chen, Gang","Width of the Hadley cell in simple and comprehensive general circulation models","Geophysical Research Letters",34,18,"sep","L18804",2007,"","","http://doi.wiley.com/10.1029/2007GL031115","","","","","","","","","","","","","","","","",""
7,"","Lu2008a","Lu, Jian; Chen, Gang; Frierson, Dargan M. W.","Response of the Zonal Mean Atmospheric Circulation to El Ni\~no versus Global Warming","Journal of Climate",21,22,"nov","5835--5851",2008,"","","http://journals.ametsoc.org/doi/abs/10.1175/2008JCLI2200.1","","","","","","","","","","","","","","","","",""
7,"","Lu2010","Lu, Jian; Chen, Gang; Frierson, Dargan M. W.","The Position of the Midlatitude Storm Track and Eddy-Driven Westerlies in Aquaplanet AGCMs","Journal of the Atmospheric Sciences",67,12,"dec","3984--4000",2010,"","","http://journals.ametsoc.org/doi/abs/10.1175/2010JAS3477.1","","","","","","","","","","","","submitted","","","","",""
7,"","Lu2013","Lu, Jian; Sun, Lantao; Wu, Yutian; Chen, Gang","The role of subtropical irreversible PV mixing in the zonal mean circulation response to global warming-like thermal forcing","Journal of Climate",27,6,"dec","2297--2316",2013,"","","http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-13-00372.1","","","","","","","","","","","","","","","","",""
7,"","Lu2014","Lu, Jian; Ruby Leung, L.; Yang, Qing; Chen, Gang; Collins, William D.; Li, Fuyu; Jason Hou, Z.; Feng, Xuelei","The robust dynamical contribution to precipitation extremes in idealized warming simulations across model resolutions","Geophysical Research Letters",41,8,"apr","2971--2978",2014,"","","http://doi.wiley.com/10.1002/2014GL059532","","","","","","","","","","","","","","","","",""
7,"","Lu2015","Lu, Jian; Chen, Gang; Leung, L. Ruby; Burrows, D. Alex; Yang, Qing; Sakaguchi, Koichi; Hagos, Samson","Toward the Dynamical Convergence on the Jet Stream in Aquaplanet AGCMs","Journal of Climate",28,17,"sep","6763--6782",2015,"","","http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-14-00761.1","","","","","","","","","","","","","","","","",""
7,"","Lu2017a","Lu, Jian; Sakaguchi, Koichi; Yang, Qing; Leung, L. Ruby; Chen, Gang; Zhao, Chun; Swenson, Erik; Hou, Zhangshuan J.","Examining the Hydrological Variations in an Aquaplanet World Using Wave Activity Transformation","Journal of Climate",30,7,"apr","2559--2576",2017,"","","http://journals.ametsoc.org/doi/10.1175/JCLI-D-16-0561.1","","","","","","","","","","","","","AbstractBuilding on the recent advent of the concept of finite-amplitude wave activity, a contour-following diagnostics for column water vapor (CWV) is developed and applied to a pair of aquaplanet model simulations to understand and quantify the higher moments in the global hydrological cycle. The Lagrangian nature of the diagnostics leads to a more tractable formalism for the transient, zonally asymmetric component of the hydrological cycle, with a strong linear relation emerging between the wave activity and the wave component of precipitation minus evaporation (). The dry-versus-wet disparity in the transient hydrological cycle is measured by , and it is found to increase at a super-Clausius–Clapeyron rate at the poleward side of the mean storm track in response to a uniform sea surface temperature (SST) warming and the meridional structure of the increase can be largely attributed to the change of the meridional stirring scale of the midlatitude Rossby waves. Further scaling for indicates that the ra...","","Extratropical cyclones,Hydrologic cycle,Lagrangian circulation/transport,Transport","",""
7,"","Martineau2017","Martineau, Patrick; Chen, Gang; Burrows, D. Alex","Wave Events: Climatology, Trends, and Relationship to Northern Hemisphere Winter Blocking and Weather Extremes","Journal of Climate",30,15,"aug","5675--5697",2017,"","","http://journals.ametsoc.org/doi/10.1175/JCLI-D-16-0692.1","","","","","","","","","","","","","AbstractDiagnostics of finite amplitude Local Wave Activity (LWA) are applied on the 500-hPa geopotential height field to diagnose persistent synoptic weather events of anomalously large wave activity in the Northern Hemisphere. By considering the cyclonic and anticyclonic components of LWA separately, persistent weather systems associated with large-amplitude troughs and ridges are detected. While anticyclonic wave events are predominantly found over Europe and Alaska, cyclonic wave events are usually occurring over East Asia and Northeastern Canada. Those preferred regions correspond to the location of planetary-scale ridges and troughs, which contribute, together with transient anomalies, to the formation of wave events. Although wave events are not blocking events per definition, they are typically associated with increased blocking in their vicinity. Their spatial relationship to blocking, however, varies depending on their cyclonic or anticyclonic nature and the type of wave-breaking signatures. Wav...","","","",""
7,"","Martineau2018","Martineau, Patrick; Chen, Gang; Son, Seok-Woo; Kim, Joowan","Lower-stratospheric control of the frequency of sudden stratospheric warming events","Journal of Geophysical Research: Atmospheres",,,"feb","",2018,"","","http://doi.wiley.com/10.1002/2017JD027648","","","","","","","","","","","","","","","","",""
7,"","McDonald2016","McDonald, George D.; Hayes, Alexander G.; Ewing, Ryan C.; Lora, Juan M.; Newman, Claire E.; Tokano, Tetsuya; Lucas, Antoine; Soto, Alejandro; Chen, Gang","Variations in Titan's dune orientations as a result of orbital forcing","Icarus",270,,"","197--210",2016,"","","http://dx.doi.org/10.1016/j.icarus.2015.11.036","","","","","","Elsevier Inc.","","","","","","","Wind-blown dunes are a record of the climatic history in Titan's equatorial region. Through modeling of the climatic conditions associated with Titan's historical orbital configurations (arising from apsidal precessions of Saturn's orbit), we present evidence that the orientations of the dunes are influenced by orbital forcing. Analysis of 3 Titan general circulation models (GCMs) in conjunction with a sediment transport model provides the first direct intercomparison of results from different Titan GCMs. We report variability in the dune orientations predicted for different orbital epochs of up to 70°. Although the response of the GCMs to orbital forcing varies, the orbital influence on the dune orientations is found to be significant across all models. Furthermore, there is near agreement among the two models run with surface topography, with 3 out of the 5 dune fields matching observation for the most recent orbital cycle. Through comparison with observations by Cassini, we find situations in which the observed dune orientations are in best agreement with those modeled for previous orbital configurations or combinations thereof, representing a larger portion of the cycle. We conclude that orbital forcing could be an important factor in governing the present-day dune orientations observed on Titan and should be considered when modeling dune evolution.","","Atmospheres, dynamics,Titan,Titan, atmosphere,Titan, surface","",""
7,"","Ming2011","Ming, Yi; Ramaswamy, V.; Chen, Gang","A Model Investigation of Aerosol-Induced Changes in Boreal Winter Extratropical Circulation","Journal of Climate",24,23,"dec","6077--6091",2011,"","","http://journals.ametsoc.org/doi/abs/10.1175/2011JCLI4111.1","","","","","","","","","","","","","","","","",""
7,"","Nie2013","Nie, Yu; Zhang, Yang; Yang, Xiu-Qun; Chen, Gang","Baroclinic anomalies associated with the Southern Hemisphere Annular Mode: Roles of synoptic and low-frequency eddies","Geophysical Research Letters",40,10,"may","2361--2366",2013,"","","http://doi.wiley.com/10.1002/grl.50396","","","","","","","","","","","","","","","","",""
7,"","Nie2014","Nie, Yu; Zhang, Yang; Chen, Gang; Yang, Xiu-qun; Burrows, D.  Alex","Quantifying barotropic and baroclinic eddy feedbacks in the persistence of the Southern Annular Mode","Geophysical Research Letters",41,23,"dec","8636--8644",2014,"","","http://doi.wiley.com/10.1002/2014GL062210","","","","","","","","","","","","","","","10.1002/2014GL062210 and SAM,barotropic/baroclinic eddy feedback,eddy-mean flow interactions,finite amplitude wave activity diagnostic","",""
7,"","Nie2015","Nie, Yu; Zhang, Yang; Chen, Gang; Yang, Xiu-Qun","Delineating the Barotropic and Baroclinic Mechanisms in the Midlatitude Eddy-Driven Jet Response to Lower-Tropospheric Thermal Forcing","Journal of the Atmospheric Sciences",73,1,"jan","429--448",2016,"","","http://journals.ametsoc.org/doi/10.1175/JAS-D-15-0090.1","","","","","","","","","","","","","","","","",""
7,"","Palipane2013","Palipane, Erool; Lu, Jian; Chen, Gang; Kinter, James L.","Improved annular mode variability in a global atmospheric general circulation model with 16 km horizontal resolution","Geophysical Research Letters",40,18,"sep","4893--4899",2013,"","","http://doi.wiley.com/10.1002/grl.50649","","","","","","","","","","","","","","","","",""
7,"","Palipane2016","Palipane, Erool; Lu, Jian; Staten, Paul; Chen, Gang; Schneider, Edwin K.","Investigating the zonal wind response to SST warming using transient ensemble AGCM experiments","Climate Dynamics",,,"apr","",2016,"","","http://link.springer.com/10.1007/s00382-016-3092-9","","","","","","Springer Berlin Heidelberg","","","","","","","","","Effective diffusivity,Finite amplitude wave activity,Greenhouse warming,Phase speed,Wave reflection,effective,finite amplitude,greenhouse warming,phase speed,wave activity,wave reflection","",""
7,"","Solomon2012","Solomon, Abraham; Chen, Gang; Lu, Jian","Finite-amplitude Lagrangian-mean wave activity applied to the baroclinic eddy life-cycle","J. Atmos. Sci.",69,10,"oct","3013--3027",2012,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-11-0294.1","","","","","","","","","","","","","","","","",""
7,"","Sun2011","Sun, Lantao; Robinson, Walter A.; Chen, Gang","The Role of Planetary Waves in the Downward Influence of Stratospheric Final Warming Events","Journal of the Atmospheric Sciences",68,12,"dec","2826--2843",2011,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-11-014.1","","","","","","","","","","","","From Duplicate 2 ( The Role of Planetary Waves in the Downward Influence of Stratospheric Final Warming Events - Sun, Lantao; Robinson, Walter a.; Chen, Gang ) ","","","","",""
7,"","Sun2012","Sun, Lantao; Robinson, Walter A.; Chen, Gang","The Predictability of Stratospheric Warming Events: More from the Troposphere or the Stratosphere?","Journal of the Atmospheric Sciences",69,2,"feb","768--783",2012,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-11-0144.1","","","","","","","","","","","","","","","","",""
7,"","Sun2013","Sun, Lantao; Chen, Gang; Lu, Jian","Sensitivities and Mechanisms of the Zonal Mean Atmospheric Circulation Response to Tropical Warming","Journal of the Atmospheric Sciences",70,8,"aug","2487--2504",2013,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-12-0298.1","","","","","","","","","","","","","","","","",""
7,"","Sun2014","Sun, Lantao; Chen, Gang; Robinson, Walter A.","The Role of Stratospheric Polar Vortex Breakdown in Southern Hemisphere Climate Trends","Journal of the Atmospheric Sciences",,,"apr","2335--2353",2014,"","","http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-13-0290.1","","","","","","","","","","","","","AbstractThis paper investigates the connection between the delay in the final breakdown of the stratospheric polar vortex, the stratospheric final warming (SFW), and Southern Hemisphere climate trends. We first analyze ERA-Interim reanalysis and three climate model outputs with different climate forcings. Climate trends appear when there is a delay in the timing of SFWs. When regressed onto the SFW dates (which reflects the anomaly when the SFW is delayed for one standard deviation of its onset dates), the anomaly pattern bears a resemblance to the observed climate trends, for all the model outputs, even without any trends. This suggests that the stratospheric and tropospheric circulations are organized by the timing of SFWs, in both the interannual time scale and climate trends due to external forcings.We further explore the role of the SFW using a simplified dynamical model, in which the ozone depletion is mimicked by a springtime polar stratospheric cooling. The responses of zonal-mean atmospheric circ...","","","",""
7,"","Wu2018","Wu, Yutian; Chen, Gang; Taylor, Lindsey; Zhang, Pengfei","On the Linkage Between the Asian Summer Monsoon and Tropopause Folds","Journal of Geophysical Research: Atmospheres",123,4,"feb","2037--2049",2018,"","","http://doi.wiley.com/10.1002/2017JD027870","","","","","","","","","","","","","","","asian summer monsoon,extreme rainfall,rossby wave breaking,tropopause folds","",""

## Import pandas

We are using the very handy pandas library for dataframes.

In [16]:
import pandas as pd

In [44]:
publications = pd.read_csv("publications.csv", sep=",", header=0)
publications

,BibliographyType,ISBN,Identifier,Author,Title,Journal,Volume,Number,Month,Pages,...,Howpublished,Institution,Organizations,School,Annote,Custom1,Custom2,Custom3,Custom4,Custom5
0,7,NaN,Burrows2015,"Burrows, D. Alex; Chen, Gang; Sun, Lantao",Barotropic and Baroclinic Eddy Feedbacks in th...,Journal of the Atmospheric Sciences,74.0,1,jan,111--132,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,NaN,Chen2007a,"Chen, Gang; Held, Isaac M.; Robinson, Walter A.",Sensitivity of the Latitude of the Surface Wes...,Journal of the Atmospheric Sciences,64.0,8,aug,2899--2915,...,NaN,NaN,NaN,NaN,From Duplicate 2 (Sensitivity of the Latitude ...,NaN,NaN,NaN,NaN,NaN
2,7,NaN,Chen2007b,"Chen, Gang; Held, Isaac M.",Phase speed spectra and the recent poleward sh...,Geophysical Research Letters,34.0,21,nov,L21805,...,NaN,NaN,NaN,NaN,From Duplicate 2 ( Phase speed spectra and the...,NaN,NaN,NaN,NaN,NaN
3,7,NaN,Chen2008,"Chen, Gang; Lu, Jian; Frierson, Dargan M. W.",Phase Speed Spectra and the Latitude of Surfac...,Journal of Climate,21.0,22,nov,5942--5959,...,NaN,NaN,NaN,NaN,From Duplicate 2 (Phase Speed Spectra and the ...,NaN,NaN,NaN,NaN,NaN
4,7,NaN,Chen2008b,"Chen, Gang; Zurita-Gotor, Pablo",The Tropospheric Jet Response to Prescribed Zo...,Journal of the Atmospheric Sciences,65.0,7,jul,2254--2271,...,NaN,NaN,NaN,NaN,From Duplicate 1 (The tropospheric jet respons...,NaN,NaN,NaN,NaN,NaN
5,7,NaN,Chen2009,"Chen, Gang; Plumb, R. Alan",Quantifying the Eddy Feedback and the Persiste...,Journal of the Atmospheric Sciences,66.0,12,dec,3707--3720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,Chen2010,"Chen, Gang; Plumb, R. Alan; Lu, Jian",Sensitivities of zonal mean atmospheric circul...,Geophysical Research Letters,37.0,12,jun,NaN,...,NaN,NaN,NaN,NaN,in press,NaN,NaN,NaN,NaN,NaN
7,7,NaN,Chen2011,"Chen, Gang; Ming, Yi; Singer, Noah D.; Lu, Jian",Testing the Clausius-Clapeyron constraint on t...,Geophysical Research Letters,38.0,NaN,feb,L04807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7,NaN,Chen2011c,"Chen, Gang; Sun, Lantao",Mechanisms of the Tropical Upwelling Branch of...,Journal of the Atmospheric Sciences,68.0,12,dec,2878--2892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7,NaN,Chen2013c,"Chen, Gang; Lu, Jian; Sun, Lantao",Delineating the Eddy–Zonal Flow Interaction in...,Journal of the Atmospheric Sciences,70.0,7,jul,2214--2233,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7,NaN,Chen2013d,"Chen, Gang",The Mean Meridional Circulation of the Atmosph...,Journal of the Atmospheric Sciences,70.0,7,jul,2197--2213,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,7,NaN,Chen2014,"Chen, Gang; Plumb, R. Alan",Effective Isentropic Diffusivity of Tropospher...,Journal of the Atmospheric Sciences,71.0,9,sep,3499--3520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,7,0094-8276,Chen2015,"Chen, Gang; Lu, Jian; Burrows, D. Alex; Leung,...",Local finite-amplitude wave activity as an obj...,Geophysical Research Letters,42.0,24,dec,"10,952--10,960",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Blocking,Extreme weather,Local wave activity,W...",NaN,NaN
13,7,NaN,Chen2017,"Chen, Gang; Orbe, Clara; Waugh, Darryn W.",The role of monsoon-like zonally asymmetric he...,Journal of Geophysical Research: Atmospheres,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,7,NaN,Domeisen2013,"Domeisen, Daniela I. V.; Sun, Lantao; Chen, Gang",The role of synoptic eddies in the tropospheri...,Geophysical Research Letters,NaN,NaN,sep,4933--4937,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7,NaN,Fang2011a,"Fang, Yuanyuan; Fiore, Arlene M.; Horowitz, La...",The impacts of changing transport and precipit...,Journal of Geophysical Research,116.0,D18,sep,D18303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7,NaN,Frierson2007b,"Frierson, Dargan M. W.; Lu, Jian; Chen, Gang",Width of the Hadley cell in simple and compreh...,Geophysical Research Letters,34.0,18,sep,L18804,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,7,NaN,Lu2008a,"Lu, Jian; Chen, Gang; Frierson, Dargan M. W.",Response of the Zonal Mean Atmospheric Circula...,Journal of Climate,21.0,22,nov,5835--5851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,7,NaN,Lu2010,"Lu, Jian; Chen, Gang; Frierson, Dargan M. W.",The Position of the Midlatitude Storm Track an...,Journal of the Atmospheric Sciences,67.0,12,dec,3984--4000,...,NaN,NaN,NaN,NaN,submitted,NaN,NaN,NaN,NaN,NaN
19,7,NaN,Lu2013,"Lu, Jian; Sun, Lantao; Wu, Yutian; Chen, Gang",The role of subtropical irreversible PV mixing...,Journal of Climate,27.0,6,dec,2297--2316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7,NaN,Lu2014,"Lu, Jian; Ruby Leung, L.; Yang, Qing; Chen, Ga...",The robust dynamical contribution to precipita...,Geophysical Research Letters,41.0,8,apr,2971--2978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,7,NaN,Lu2015,"Lu, Jian; Chen, Gang; Leung, L. Ruby; Burrows,...",Toward the Dynamical Convergence on the Jet St...,Journal of Climate,28.0,17,sep,6763--6782,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,7,NaN,Lu2017a,"Lu, Jian; Sakaguchi, Koichi; Yang, Qing; Leung...",Examining the Hydrological Variations in an Aq...,Journal of Climate,30.0,7,apr,2559--2576,...,NaN,NaN,NaN,NaN,NaN,AbstractBuilding on the recent advent of the c...,NaN,"Extratropical cyclones,Hydrologic cycle,Lagran...",NaN,NaN
23,7,NaN,Martineau2017,"Martineau, Patrick; Chen, Gang; Burrows, D. Alex","Wave Events: Climatology, Trends, and Relation...",Journal of Climate,30.0,15,aug,5675--5697,...,NaN,NaN,NaN,NaN,NaN,AbstractDiagnostics of finite amplitude Local ...,NaN,NaN,NaN,NaN
24,7,NaN,Martineau2018,"Martineau, Patrick; Chen, Gang; Son, Seok-Woo;...",Lower-stratospheric control of the frequency o...,Journal of Geophysical Research: Atmospheres,NaN,NaN,feb,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,7,NaN,McDonald2016,"McDonald, George D.; Hayes, Alexander G.; Ewin...",Variations in Titan's dune orientations as a r...,Icarus,270.0,NaN,NaN,197--210,...,NaN,NaN,NaN,NaN,NaN,Wind-blown dunes are a record of the climatic ...,NaN,"Atmospheres, dynamics,Titan,Titan, atmosphere,...",NaN,NaN
26,7,NaN,Ming2011,"Ming, Yi; Ramaswamy, V.; Chen, Gang",A Model Investigation of Aerosol-Induced Chang...,Journal of Climate,24.0,23,dec,6077--6091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,7,NaN,Nie2013,"Nie, Yu; Zhang, Yang; Yang, Xiu-Qun; Chen, Gang",Baroclinic anomalies associated with the South...,Geophysical Research Letters,40.0,10,may,2361--2366,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,7,NaN,Nie2014,"Nie, Yu; Zhang, Yang; Chen, Gang; Yang, Xiu-qu...",Quantifying barotropic and baroclinic eddy fee...,Geophysical Research Letters,41.0,23,dec,8636--8644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10.1002/2014GL062210 and SAM,barotropic/barocl...",NaN,NaN
29,7,NaN,Nie2015,"Nie, Yu; Zhang, Yang; Chen, Gang; Yang, Xiu-Qun",Delineating the Barotropic and Baroclinic Mech...,Journal of the Atmospheric Sciences,73.0,1,jan,429--448,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,7,NaN,Palipane2013,"Palipane, Erool; Lu, Jian; Chen, Gang; Kinter,...",Improved annular mode variability in a global ...,Geophysical Research Letters,40.0,18,sep,4893--4899,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,7,NaN,Palipane2016,"Palipane, Erool; Lu, Jian; Staten, Paul; Chen,...",Investigating the zonal wind response to SST w...,Climate Dynamics,NaN,NaN,apr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Effective diffusivity,Finite amplitude wave ac...",NaN,NaN
32,7,NaN,Solomon2012,"Solomon, Abraham; Chen, Gang; Lu, Jian",Finite-amplitude Lagrangian-mean wave activity...,J. Atmos. Sci.,69.0,10,oct,3013--3027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,7,NaN,Sun2011,"Sun, Lantao; Robinson, Walter A.; Chen, Gang",The Role of Planetary Waves in the Downward In...,Journal of the Atmospheric Sciences,68.0,12,dec,2826--2843,...,NaN,NaN,NaN,NaN,From Duplicate 2 ( The Role of Planetary Waves...,NaN,NaN,NaN,NaN,NaN
34,7,NaN,Sun2012,"Sun, Lantao; Robinson, Walter A.; Chen, Gang",The Predictability of Stratospheric Warming Ev...,Journal of the Atmospheric Sciences,69.0,2,feb,768--783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,7,NaN,Sun2013,"Sun, Lantao; Chen, Gang; Lu, Jian",Sensitivities and Mechanisms of the Zonal Mean...,Journal of the Atmospheric Sciences,70.0,8,aug,2487--2504,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,7,NaN,Sun2014,"Sun, Lantao; Chen, Gang; Robinson, Walter A.",The Role of Stratospheric Polar Vortex Breakdo...,Journal of the Atmospheric Sciences,NaN,NaN,apr,2335--2353,...,NaN,NaN,NaN,NaN,NaN,AbstractThis paper investigates the connection...,NaN,NaN,NaN,NaN
37,7,NaN,Wu2018,"Wu, Yutian; Chen, Gang; Taylor, Lindsey; Zhang...",On the Linkage Between the Asian Summer Monsoo...,Journal of Geophysical Research: Atmospheres,123.0,4,feb,2037--2049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"asian summer monsoon,extreme rainfall,rossby w...",NaN,NaN
38,7,NaN,Xue2017,"Xue, Daokai; Lu, Jian; Sun, Lantao; Chen, Gang...",Local increase of anticyclonic wave activity o...,Geophysical Research Letters,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,7,NaN,Yang2014a,"Yang, Huang; Chen, Gang; Domeisen, Daniela I. ...",Sensitivities of the Lower-Stratospheric Trans...,Journal of the Atmospheric Sciences,71.0,7,jul,2674--2694,...,NaN,NaN,NaN,NaN,NaN,AbstractThe sensitivities of the Brewer-Dobson...,NaN,NaN,NaN,NaN
40,7,NaN,Yang2014b,"Yang, Huang; Sun, Lantao; Chen, Gang",Separating the Mechanisms of Transient Respons...,Journal of the Atmospheric Sciences,72.0,2,feb,763--773,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,7,NaN,Yang2015,"Yang, Huang; Chen, Gang; Tang, Qi; Hess, Peter G.",Quantifying isentropic stratosphere-tropospher...,Journal of Geophysical Research: Atmospheres,121.0,7,apr,3372--3387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.1002/2015JD024180 and stratosphere-troposph...,NaN,NaN
42,7,NaN,Zhang2012,"Zhang, Yang; Yang, Xiu-Qun; Nie, Yu; Chen, Gang",Annular Mode-Like Variation in a Multilayer Qu...,Journal of the Atmospheric Sciences,69.0,10,oct,2940--2958,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Escape special characters

YAML is very picky about how it takes a valid string, so we are replacing single and double quotes (and ampersands) with their HTML encoded equivilents. This makes them look not so readable in raw format, but they are parsed and rendered nicely.

In [45]:
html_escape_table = {
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;"
    }

def html_escape(text):
    """Produce entities within text."""
    return "".join(html_escape_table.get(c,c) for c in text)

In [46]:
publications

,BibliographyType,ISBN,Identifier,Author,Title,Journal,Volume,Number,Month,Pages,...,Howpublished,Institution,Organizations,School,Annote,Custom1,Custom2,Custom3,Custom4,Custom5
0,7,NaN,Burrows2015,"Burrows, D. Alex; Chen, Gang; Sun, Lantao",Barotropic and Baroclinic Eddy Feedbacks in th...,Journal of the Atmospheric Sciences,74.0,1,jan,111--132,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,NaN,Chen2007a,"Chen, Gang; Held, Isaac M.; Robinson, Walter A.",Sensitivity of the Latitude of the Surface Wes...,Journal of the Atmospheric Sciences,64.0,8,aug,2899--2915,...,NaN,NaN,NaN,NaN,From Duplicate 2 (Sensitivity of the Latitude ...,NaN,NaN,NaN,NaN,NaN
2,7,NaN,Chen2007b,"Chen, Gang; Held, Isaac M.",Phase speed spectra and the recent poleward sh...,Geophysical Research Letters,34.0,21,nov,L21805,...,NaN,NaN,NaN,NaN,From Duplicate 2 ( Phase speed spectra and the...,NaN,NaN,NaN,NaN,NaN
3,7,NaN,Chen2008,"Chen, Gang; Lu, Jian; Frierson, Dargan M. W.",Phase Speed Spectra and the Latitude of Surfac...,Journal of Climate,21.0,22,nov,5942--5959,...,NaN,NaN,NaN,NaN,From Duplicate 2 (Phase Speed Spectra and the ...,NaN,NaN,NaN,NaN,NaN
4,7,NaN,Chen2008b,"Chen, Gang; Zurita-Gotor, Pablo",The Tropospheric Jet Response to Prescribed Zo...,Journal of the Atmospheric Sciences,65.0,7,jul,2254--2271,...,NaN,NaN,NaN,NaN,From Duplicate 1 (The tropospheric jet respons...,NaN,NaN,NaN,NaN,NaN
5,7,NaN,Chen2009,"Chen, Gang; Plumb, R. Alan",Quantifying the Eddy Feedback and the Persiste...,Journal of the Atmospheric Sciences,66.0,12,dec,3707--3720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,Chen2010,"Chen, Gang; Plumb, R. Alan; Lu, Jian",Sensitivities of zonal mean atmospheric circul...,Geophysical Research Letters,37.0,12,jun,NaN,...,NaN,NaN,NaN,NaN,in press,NaN,NaN,NaN,NaN,NaN
7,7,NaN,Chen2011,"Chen, Gang; Ming, Yi; Singer, Noah D.; Lu, Jian",Testing the Clausius-Clapeyron constraint on t...,Geophysical Research Letters,38.0,NaN,feb,L04807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7,NaN,Chen2011c,"Chen, Gang; Sun, Lantao",Mechanisms of the Tropical Upwelling Branch of...,Journal of the Atmospheric Sciences,68.0,12,dec,2878--2892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7,NaN,Chen2013c,"Chen, Gang; Lu, Jian; Sun, Lantao",Delineating the Eddy–Zonal Flow Interaction in...,Journal of the Atmospheric Sciences,70.0,7,jul,2214--2233,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7,NaN,Chen2013d,"Chen, Gang",The Mean Meridional Circulation of the Atmosph...,Journal of the Atmospheric Sciences,70.0,7,jul,2197--2213,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,7,NaN,Chen2014,"Chen, Gang; Plumb, R. Alan",Effective Isentropic Diffusivity of Tropospher...,Journal of the Atmospheric Sciences,71.0,9,sep,3499--3520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,7,0094-8276,Chen2015,"Chen, Gang; Lu, Jian; Burrows, D. Alex; Leung,...",Local finite-amplitude wave activity as an obj...,Geophysical Research Letters,42.0,24,dec,"10,952--10,960",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Blocking,Extreme weather,Local wave activity,W...",NaN,NaN
13,7,NaN,Chen2017,"Chen, Gang; Orbe, Clara; Waugh, Darryn W.",The role of monsoon-like zonally asymmetric he...,Journal of Geophysical Research: Atmospheres,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,7,NaN,Domeisen2013,"Domeisen, Daniela I. V.; Sun, Lantao; Chen, Gang",The role of synoptic eddies in the tropospheri...,Geophysical Research Letters,NaN,NaN,sep,4933--4937,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7,NaN,Fang2011a,"Fang, Yuanyuan; Fiore, Arlene M.; Horowitz, La...",The impacts of changing transport and precipit...,Journal of Geophysical Research,116.0,D18,sep,D18303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7,NaN,Frierson2007b,"Frierson, Dargan M. W.; Lu, Jian; Chen, Gang",Width of the Hadley cell in simple and compreh...,Geophysical Research Letters,34.0,18,sep,L18804,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,7,NaN,Lu2008a,"Lu, Jian; Chen, Gang; Frierson, Dargan M. W.",Response of the Zonal Mean Atmospheric Circula...,Journal of Climate,21.0,22,nov,5835--5851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,7,NaN,Lu2010,"Lu, Jian; Chen, Gang; Frierson, Dargan M. W.",The Position of the Midlatitude Storm Track an...,Journal of the Atmospheric Sciences,67.0,12,dec,3984--4000,...,NaN,NaN,NaN,NaN,submitted,NaN,NaN,NaN,NaN,NaN
19,7,NaN,Lu2013,"Lu, Jian; Sun, Lantao; Wu, Yutian; Chen, Gang",The role of subtropical irreversible PV mixing...,Journal of Climate,27.0,6,dec,2297--2316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7,NaN,Lu2014,"Lu, Jian; Ruby Leung, L.; Yang, Qing; Chen, Ga...",The robust dynamical contribution to precipita...,Geophysical Research Letters,41.0,8,apr,2971--2978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,7,NaN,Lu2015,"Lu, Jian; Chen, Gang; Leung, L. Ruby; Burrows,...",Toward the Dynamical Convergence on the Jet St...,Journal of Climate,28.0,17,sep,6763--6782,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,7,NaN,Lu2017a,"Lu, Jian; Sakaguchi, Koichi; Yang, Qing; Leung...",Examining the Hydrological Variations in an Aq...,Journal of Climate,30.0,7,apr,2559--2576,...,NaN,NaN,NaN,NaN,NaN,AbstractBuilding on the recent advent of the c...,NaN,"Extratropical cyclones,Hydrologic cycle,Lagran...",NaN,NaN
23,7,NaN,Martineau2017,"Martineau, Patrick; Chen, Gang; Burrows, D. Alex","Wave Events: Climatology, Trends, and Relation...",Journal of Climate,30.0,15,aug,5675--5697,...,NaN,NaN,NaN,NaN,NaN,AbstractDiagnostics of finite amplitude Local ...,NaN,NaN,NaN,NaN
24,7,NaN,Martineau2018,"Martineau, Patrick; Chen, Gang; Son, Seok-Woo;...",Lower-stratospheric control of the frequency o...,Journal of Geophysical Research: Atmospheres,NaN,NaN,feb,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,7,NaN,McDonald2016,"McDonald, George D.; Hayes, Alexander G.; Ewin...",Variations in Titan's dune orientations as a r...,Icarus,270.0,NaN,NaN,197--210,...,NaN,NaN,NaN,NaN,NaN,Wind-blown dunes are a record of the climatic ...,NaN,"Atmospheres, dynamics,Titan,Titan, atmosphere,...",NaN,NaN
26,7,NaN,Ming2011,"Ming, Yi; Ramaswamy, V.; Chen, Gang",A Model Investigation of Aerosol-Induced Chang...,Journal of Climate,24.0,23,dec,6077--6091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,7,NaN,Nie2013,"Nie, Yu; Zhang, Yang; Yang, Xiu-Qun; Chen, Gang",Baroclinic anomalies associated with the South...,Geophysical Research Letters,40.0,10,may,2361--2366,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,7,NaN,Nie2014,"Nie, Yu; Zhang, Yang; Chen, Gang; Yang, Xiu-qu...",Quantifying barotropic and baroclinic eddy fee...,Geophysical Research Letters,41.0,23,dec,8636--8644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10.1002/2014GL062210 and SAM,barotropic/barocl...",NaN,NaN
29,7,NaN,Nie2015,"Nie, Yu; Zhang, Yang; Chen, Gang; Yang, Xiu-Qun",Delineating the Barotropic and Baroclinic Mech...,Journal of the Atmospheric Sciences,73.0,1,jan,429--448,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,7,NaN,Palipane2013,"Palipane, Erool; Lu, Jian; Chen, Gang; Kinter,...",Improved annular mode variability in a global ...,Geophysical Research Letters,40.0,18,sep,4893--4899,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,7,NaN,Palipane2016,"Palipane, Erool; Lu, Jian; Staten, Paul; Chen,...",Investigating the zonal wind response to SST w...,Climate Dynamics,NaN,NaN,apr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Effective diffusivity,Finite amplitude wave ac...",NaN,NaN
32,7,NaN,Solomon2012,"Solomon, Abraham; Chen, Gang; Lu, Jian",Finite-amplitude Lagrangian-mean wave activity...,J. Atmos. Sci.,69.0,10,oct,3013--3027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,7,NaN,Sun2011,"Sun, Lantao; Robinson, Walter A.; Chen, Gang",The Role of Planetary Waves in the Downward In...,Journal of the Atmospheric Sciences,68.0,12,dec,2826--2843,...,NaN,NaN,NaN,NaN,From Duplicate 2 ( The Role of Planetary Waves...,NaN,NaN,NaN,NaN,NaN
34,7,NaN,Sun2012,"Sun, Lantao; Robinson, Walter A.; Chen, Gang",The Predictability of Stratospheric Warming Ev...,Journal of the Atmospheric Sciences,69.0,2,feb,768--783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,7,NaN,Sun2013,"Sun, Lantao; Chen, Gang; Lu, Jian",Sensitivities and Mechanisms of the Zonal Mean...,Journal of the Atmospheric Sciences,70.0,8,aug,2487--2504,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,7,NaN,Sun2014,"Sun, Lantao; Chen, Gang; Robinson, Walter A.",The Role of Stratospheric Polar Vortex Breakdo...,Journal of the Atmospheric Sciences,NaN,NaN,apr,2335--2353,...,NaN,NaN,NaN,NaN,NaN,AbstractThis paper investigates the connection...,NaN,NaN,NaN,NaN
37,7,NaN,Wu2018,"Wu, Yutian; Chen, Gang; Taylor, Lindsey; Zhang...",On the Linkage Between the Asian Summer Monsoo...,Journal of Geophysical Research: Atmospheres,123.0,4,feb,2037--2049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"asian summer monsoon,extreme rainfall,rossby w...",NaN,NaN
38,7,NaN,Xue2017,"Xue, Daokai; Lu, Jian; Sun, Lantao; Chen, Gang...",Local increase of anticyclonic wave activity o...,Geophysical Research Letters,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,7,NaN,Yang2014a,"Yang, Huang; Chen, Gang; Domeisen, Daniela I. ...",Sensitivities of the Lower-Stratospheric Trans...,Journal of the Atmospheric Sciences,71.0,7,jul,2674--2694,...,NaN,NaN,NaN,NaN,NaN,AbstractThe sensitivities of the Brewer-Dobson...,NaN,NaN,NaN,NaN
40,7,NaN,Yang2014b,"Yang, Huang; Sun, Lantao; Chen, Gang",Separating the Mechanisms of Transient Respons...,Journal of the Atmospheric Sciences,72.0,2,feb,763--773,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,7,NaN,Yang2015,"Yang, Huang; Chen, Gang; Tang, Qi; Hess, Peter G.",Quantifying isentropic stratosphere-tropospher...,Journal of Geophysical Research: Atmospheres,121.0,7,apr,3372--3387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.1002/2015JD024180 and stratosphere-troposph...,NaN,NaN
42,7,NaN,Zhang2012,"Zhang, Yang; Yang, Xiu-Qun; Nie, Yu; Chen, Gang",Annular Mode-Like Variation in a Multilayer Qu...,Journal of the Atmospheric Sciences,69.0,10,oct,2940--2958,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
import os
import calendar
import numpy
for row, item in publications.iterrows():

    year = item.Year
    if pd.isnull(item.Month): 
        month = 1
    else:
        month = list(calendar.month_abbr).index(item.Month.capitalize())
    
    pub_date = str(year) + "-" + str(month) + "-" + "1"
    md_filename   = pub_date + "-" + item.Identifier + ".md"
    html_filename = pub_date + "-" + item.Identifier
    
    ## YAML variables
    
    md = "---\ntitle: \""   + item.Title + '"\n'
    
    md += """collection: publications"""
    
    md += """\npermalink: /publication/""" + html_filename

    md += "\ndate: " + str(pub_date) 
    
    md += "\nvenue: '" + html_escape(item.Journal) + "'"
    
    if len(str(item.URL)) > 5:
        md += "\npaperurl: '" + item.URL + "'"
    
    md += "\ncitation: "
    
    md += "\n---"

    md_filename = os.path.basename(md_filename)
    
    with open("../_publications/" + md_filename, 'w') as f:
        f.write(md)

Barotropic and Baroclinic Eddy Feedbacks in the Midlatitude Jet Variability and Responses to Climate Change–Like Thermal Forcings
Sensitivity of the Latitude of the Surface Westerlies to Surface Friction
Phase speed spectra and the recent poleward shift of Southern Hemisphere surface westerlies
Phase Speed Spectra and the Latitude of Surface Westerlies: Interannual Variability and Global Warming Trend
The Tropospheric Jet Response to Prescribed Zonal Forcing in an Idealized Atmospheric Model
Quantifying the Eddy Feedback and the Persistence of the Zonal Index in an Idealized Atmospheric Model
Sensitivities of zonal mean atmospheric circulation to SST warming in an aqua-planet model
Testing the Clausius-Clapeyron constraint on the aerosol-induced changes in mean and extreme precipitation
Mechanisms of the Tropical Upwelling Branch of the Brewer–Dobson Circulation: The Role of Extratropical Waves
Delineating the Eddy–Zonal Flow Interaction in the Atmospheric Circulation Response to Climate Forcing: Uniform SST Warming in an Idealized Aquaplanet Model
The Mean Meridional Circulation of the Atmosphere Using the Mass above Isentropes as the Vertical Coordinate
Effective Isentropic Diffusivity of Tropospheric Transport
Local finite-amplitude wave activity as an objective diagnostic of midlatitude extreme weather
The role of monsoon-like zonally asymmetric heating in interhemispheric transport
The role of synoptic eddies in the tropospheric response to stratospheric variability
The impacts of changing transport and precipitation on pollutant distributions in a future climate
Width of the Hadley cell in simple and comprehensive general circulation models
Response of the Zonal Mean Atmospheric Circulation to El Ni\~no versus Global Warming
The Position of the Midlatitude Storm Track and Eddy-Driven Westerlies in Aquaplanet AGCMs
The role of subtropical irreversible PV mixing in the zonal mean circulation response to global warming-like thermal forcing
The robust dynamical contribution to precipitation extremes in idealized warming simulations across model resolutions
Toward the Dynamical Convergence on the Jet Stream in Aquaplanet AGCMs
Examining the Hydrological Variations in an Aquaplanet World Using Wave Activity Transformation
Wave Events: Climatology, Trends, and Relationship to Northern Hemisphere Winter Blocking and Weather Extremes
Lower-stratospheric control of the frequency of sudden stratospheric warming events
Variations in Titan's dune orientations as a result of orbital forcing
A Model Investigation of Aerosol-Induced Changes in Boreal Winter Extratropical Circulation
Baroclinic anomalies associated with the Southern Hemisphere Annular Mode: Roles of synoptic and low-frequency eddies
Quantifying barotropic and baroclinic eddy feedbacks in the persistence of the Southern Annular Mode
Delineating the Barotropic and Baroclinic Mechanisms in the Midlatitude Eddy-Driven Jet Response to Lower-Tropospheric Thermal Forcing
Improved annular mode variability in a global atmospheric general circulation model with 16 km horizontal resolution
Investigating the zonal wind response to SST warming using transient ensemble AGCM experiments
Finite-amplitude Lagrangian-mean wave activity applied to the baroclinic eddy life-cycle
The Role of Planetary Waves in the Downward Influence of Stratospheric Final Warming Events
The Predictability of Stratospheric Warming Events: More from the Troposphere or the Stratosphere?
Sensitivities and Mechanisms of the Zonal Mean Atmospheric Circulation Response to Tropical Warming
The Role of Stratospheric Polar Vortex Breakdown in Southern Hemisphere Climate Trends
On the Linkage Between the Asian Summer Monsoon and Tropopause Folds
Local increase of anticyclonic wave activity over northern Eurasia under amplified Arctic warming
Sensitivities of the Lower-Stratospheric Transport and Mixing to Tropical SST Heating
Separating the Mechanisms of Transient Responses to Stratospheric Ozone Depletion–Like Cooling in an Idealized Atmospheric Model
Quantifying isentropic stratosphere-troposphere exchange of ozone
Annular Mode-Like Variation in a Multilayer Quasigeostrophic Model

## Creating the markdown files

This is where the heavy lifting is done. This loops through all the rows in the TSV dataframe, then starts to concatentate a big string (```md```) that contains the markdown for each type. It does the YAML metadata first, then does the description for the individual page.

These files are in the publications directory, one directory below where we're working from.

In [5]:
import os
for row, item in publications.iterrows():
    
    md_filename = str(item.Year) + "-" + item.Title + ".md"
    html_filename = str(item.pub_date) + "-" + item.Title
    year = item.pub_date[:4]
    
    ## YAML variables
    
    md = "---\ntitle: \""   + item.title + '"\n'
    
    md += """collection: publications"""
    
    md += """\npermalink: /publication/""" + html_filename
    
    if len(str(item.excerpt)) > 5:
        md += "\nexcerpt: '" + html_escape(item.excerpt) + "'"
    
    md += "\ndate: " + str(item.pub_date) 
    
    md += "\nvenue: '" + html_escape(item.venue) + "'"
    
    if len(str(item.paper_url)) > 5:
        md += "\npaperurl: '" + item.paper_url + "'"
    
    md += "\ncitation: '" + html_escape(item.citation) + "'"
    
    md += "\n---"
    
    ## Markdown description for individual page
        
    if len(str(item.excerpt)) > 5:
        md += "\n" + html_escape(item.excerpt) + "\n"
    
    if len(str(item.paper_url)) > 5:
        md += "\n[Download paper here](" + item.paper_url + ")\n" 
        
    md += "\nRecommended citation: " + item.citation
    
    md_filename = os.path.basename(md_filename)
       
    with open("../_publications/" + md_filename, 'w') as f:
        f.write(md)

In [38]:
!ls ../_publications/

2009-10-01-paper-title-number-1.md  2010-10-01-paper-title-number-2.md

In [39]:
!cat ../_publications/2009-10-01-paper-title-number-1.md

---
title: "Paper Title Number 1"
collection: publications
permalink: /publication/2009-10-01-paper-title-number-1
excerpt: 'This paper is about the number 1. The number 2 is left for future work.'
date: 2009-10-01
venue: 'Journal 1'
paperurl: 'http://academicpages.github.io/files/paper1.pdf'
citation: 'Your Name, You. (2009). &quot;Paper Title Number 1.&quot; <i>Journal 1</i>. 1(1).'
---
This paper is about the number 1. The number 2 is left for future work.

[Download paper here](http://academicpages.github.io/files/paper1.pdf)

Recommended citation: Your Name, You. (2009). "Paper Title Number 1." <i>Journal 1</i>. 1(1).